apiKey: ${WEATHER_API_KEY}
ciudad: Buenos Aires
apiUrl: https://api.weatherapi.com/v1/current.json

mails:
  remitente: ${SENDER_MAIL}
  destinatarios:
    - leojviegas@gmail.com
    - admin@clima.com
    - emergencias@clima.com
    - meteorologia@clima.com

spring:
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true