apiKey: ${WEATHER_API_KEY}
ciudad: Buenos Aires
apiUrl: https://api.weatherapi.com/v1/current.json

mailRemitente: ${SENDER_MAIL}
mailDestinatario1: admin@clima.com
mailDestinatario2: emergencias@clima.com
mailDestinatario3: meteorologia@clima.com
mailDestinatario4: admin@clima.com

spring:
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true